# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
       while read -r cmd
        do
          eval sudo $cmd
        done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   # - name: Lint with pylint
    #  run: |
        # stop the build if there are Python syntax errors or undefined names
     #   pylint src/ --errors-only --disable=all --enable=E,W,F --exit-zero
        # stop the build if there are Python syntax errors or undefined names
      #  pylint src/ --exit-zero --max-line-length=127
    #- name: Test with pytest
     # run: |
      #  pytest
    - name: Reload app
      uses: jensvog/pythonanywhere-webapp-reload-action@v1
      with: 
        host: 'www.pythonanywhere.com'
        username: easystock
        api-token: ${{secrets.EASYSTOCK_TOKEN}}
        domain-name: easystock.pythonanywhere.com
